name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build burp server
        id: docker_build_burp_server_latest
        uses: docker/build-push-action@v5
        with:
          context: ./burp-server
          file: ./burp-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/burp-server:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_burp_server_latest.outputs.digest }}

      - name: Build burp ui
        id: docker_build_burp_ui_latest
        uses: docker/build-push-action@v5
        with:
          context: ./burp-ui
          file: ./burp-ui/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/burp-ui:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_burp_ui_latest.outputs.digest }}

      - name: Build burp client
        id: docker_build_burp_client_latest
        uses: docker/build-push-action@v5
        with:
          context: ./burp-client
          file: ./burp-client/Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/burp-client:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_burp_client_latest.outputs.digest }}
